---
title: "Basic Info"
date: "`r format(Sys.time(), '%d %B, %Y')`"
author: "Unit C2"
output:
  html_document: 
    toc: yes
    toc_float: yes
    fig_width:  10
    fig_height: 7
    theme: cerulean
params:
  report: LU
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = FALSE,
  message = FALSE,
  warning = FALSE
)
```

```{r country, include=FALSE}
# country sel is specified in the UI script and taken from there
country_sel <- params$report
```

```{r load_packages, include=FALSE}
# Packages needed
library(rio)
library(tidyverse)
library(data.table)
library(dataregacc)
library(regacc)
options(dplyr.summarise.inform = FALSE)
```

```{r, data}
data<- regacc::load_xml(folder =  "data/xml",
                         country_sel = country_sel,
                         consolidate = FALSE) %>%
  arrange(date) %>%
  group_by(across(
    c(
      table_identifier,
      ref_area,
      sto,
      accounting_entry,
      activity,
      unit_measure,
      time_period
    )
  )) %>%
  slice_tail(n = 1) %>%
  ungroup() %>%
  mutate(country = str_sub(ref_area, 1, 2),
         NUTS = str_length(ref_area) - 2,
         NUTS=as.factor(NUTS)) %>%
  mutate(value = str_remove_all(value, "data/xml/NAREG_")) %>% 
  as.data.table()

NUTS2021<-dataregacc::NUTS_2021 %>% 
  filter(country %in% country_sel) %>% 
  mutate(across(c(NUTS,label),as_factor)) %>% 
  mutate(country=as.character(country)) %>% 
  as.data.table()


data<- left_join(data,NUTS2021)
```

### Periods reported by table

```{r}
# show first and last year reported
  temp<- data %>% 
    filter(!obs_status %in% c("L","M") & !is.na(obs_value) ) %>% 
    select(country,table_identifier,country,sto,accounting_entry,unit_measure, time_period) %>% 
    group_by(across(-c(time_period))) %>% 
    mutate(first=min(time_period),
           last = max(time_period)) %>% 
    select(-time_period) %>% 
    unique() %>% 
    mutate(across(everything(as.factor)))
	
	regacc::show_DT(temp)
```

### Embargo dates

```{r}
# show embargo dates
if ("embargo_date" %in% colnames(data)){
    temp<- data %>% 
      select(country,table_identifier,country,embargo_date) %>% 
      na.omit() %>% 
      unique() %>% 
      mutate(across(everything(as.factor))) %>% 
      droplevels()}

```

### Comments

```{r}
# show comments in the files
if ("comment_ts" %in% names(df)) {
    temp<- data %>% 
      select(country,table_identifier,comment_ts) %>% 
      filter(comment_ts!="xxx" & comment_ts!="") %>% 
      na.omit() %>% 
      unique() %>% 
      mutate(across(everything(as.factor))) %>% 
      droplevels()
if (nrow(temp) > 0)
  regacc::show_DT(temp) }
```

### Data not for publication

```{r}
# data not for publication, with a flag N
  temp<- data %>% 
    select(country,table_identifier,sto,activity,unit_measure,conf_status) %>% 
    filter(conf_status =="N") %>% 
    na.omit() %>% 
    unique() %>% 
    mutate(across(everything(as.factor))) %>% 
    droplevels() 

if (nrow(temp) > 0)
  regacc::show_DT(temp) 
 
```

### Flags

```{r}
# flags E,P,B,D,U
  temp<- data %>% 
    select(country,table_identifier,sto,unit_measure,obs_status,time_period) %>% 
    filter(obs_status %in% c("E","P","B","D","U")) %>% 
    na.omit() %>% 
    unique() %>% 
    mutate(across(everything(as.factor))) %>% 
    droplevels()

if (nrow(temp) > 0)
  regacc::show_DT(temp) 
```
