---
title: "Regional Accounts: Basic info from xml files"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  html_document: 
    fig_width: 12
    fig_height: 9
params:
  report: IE
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = FALSE,
  message = FALSE,
  warning = FALSE
)
```

```{r country, include=FALSE}
country <- params$report
```

```{r load_packages, include=FALSE}
# Packages needed

library(tidyverse)
library(readsdmx)
library(janitor)
library(DT)
source("utils.R")
```

```{r}
 
files<-list.files(paste0("U:/03_Regional Accounts/03D_Data Production/2021/",country,"/transmission/"),
                  pattern = "*.xml$",
                  recursive=TRUE,
                  full.names = TRUE) %>% 
  as_tibble() %>% 
  mutate(country= str_sub(value, -22,-21 )) %>% 
  mutate(table = str_sub(value, -30,-26 )) %>%
  mutate(date=map(value,file.info)) %>% 
  unnest(date) %>% 
  select(country,table,value,mtime) %>% 
  mutate(data=map(value,~read_sdmx(.x))) %>% 
  unnest(cols = c(data)) %>% 
  janitor::clean_names() %>% 
  mutate(value=str_sub(value,-36,-5))


files<- files %>%     
mutate(obs_value=as.numeric(obs_value),
         time_period=as.integer(time_period)) %>% 
  mutate_if(is.character,as.factor)


```

## Basic information {.tabset}

### Reported Periods

```{r}
temp<- files %>% 
  group_by(table,sto,activity,unit_measure,accounting_entry) %>% 
    select(value,country,time_period,sto,activity,unit_measure,accounting_entry,obs_value,obs_status) %>% 
   drop_na(obs_value) %>% 
  filter(!obs_status %in% c("M", "L")) %>% 
  mutate(first=min(time_period),
         last=max(time_period)) %>% 
  ungroup() %>% 
  select(value,country,table,sto,activity,unit_measure,accounting_entry,first,last) %>% 
  unique()

show_table(temp)
```

### Reported Geo

```{r}

temp<- files %>% 
  select(value,country,table,ref_area,time_period,sto,activity,unit_measure,accounting_entry,obs_value) %>% 
  na.omit() 

NUTS <- rio::import("data/NUTS2021.xlsx") %>% 
  rename("ref_area" = geo) %>% 
  select(-label)

temp<- left_join(temp,NUTS) %>%
  select(value,table,country,NUTS,time_period,sto,activity,unit_measure,accounting_entry) %>% 
  group_by(value,table,country,NUTS,sto,unit_measure) %>% 
  count()

show_table(temp)
```

### Flags

```{r}
  temp<- files
      
  if ("embargo_date" %in% colnames(temp)){
  temp<- temp %>% 
    select(value,country,table,ref_area,time_period,sto,activity,unit_measure,accounting_entry,obs_value, obs_status,conf_status,embargo_date) %>% 
  filter(conf_status !="F") %>% 
   na.omit() %>%  
   group_by(value,table,country,time_period,obs_status, conf_status,embargo_date) %>% 
  count()

   } else {
      temp<- temp %>% 
     select(value,table,country,time_period,sto,activity,unit_measure,accounting_entry,obs_status,conf_status) %>% 
  group_by(value,table,country,time_period,obs_status, conf_status) %>% 
  count()
 
   }
    show_table(temp)

```

### Comments

```{r}
temp<- files %>%
  ungroup() 

if ("comment_ts" %in% colnames(files)){
  temp<- temp %>% 
    select(value,country,table,sto,unit_measure,comment_ts) %>%
    na.omit() %>% 
    unique()
  
  show_table(temp)
  
} else {
print("No comments")
  }
```



