---
title: "Outliers"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  html_document: 
    code_download: true
    fig_width: 12
    fig_height: 9
params:
  country: SI
  z_score: 1.5
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = FALSE,
	message = FALSE,
	warning = FALSE
)
```

```{r country, include=FALSE}
country_sel <- params$country
z_score <- params$z_score

```


Series with a Z-score above `r z_score`.  

```{r libraries, include=FALSE}

library(tidyverse)
library(DT)
library(data.table)
library(scales)
library(rio)
library(luispack)

options(dplyr.summarise.inform = FALSE)
```

```{r data}
source("utils/theme_report.R")

NUTS2021<-luispack::NUTS_2021 %>% 
  filter(country %in% country_sel) %>% 
  mutate(across(c(NUTS,label),as_factor)) %>% 
  mutate(country=as.character(country)) %>% 
  droplevels()

df<-list.files(path="data/denodo",
           pattern= glob2rx(paste0("*",country_sel,"*")),
           full.names=TRUE) %>% 
  as_tibble() %>% 
  mutate(date=map(value,file.mtime)) %>% 
  unnest(date) %>% 
  arrange(desc(date)) %>% 
  head(1) %>% 
  select(value) %>% 
  pull() %>% 
 fread() %>% 
  mutate(NUTS=as.factor(NUTS)) %>% 
  filter(unit_measure!="PC") %>% 
  group_by(type,ref_area, table_identifier, accounting_entry,sto,activity,unit_measure) %>%
  arrange(time_period,.by_group = TRUE) %>% 
  mutate(gr=round(obs_value/lag(obs_value)*100-100,1)) %>% 
  mutate(zscore = (gr - mean(gr, na.rm = TRUE)) / sd(gr, na.rm = TRUE) ) %>% 
  ungroup()

min_period <- df %>%
  select(-zscore,-gr) %>% 
  pivot_wider(names_from=type,
              values_from=obs_value) %>% 
  mutate(rev=T-V) %>% 
  filter(rev!=0) %>% 
  select(table_identifier,ref_area,accounting_entry,sto,activity,unit_measure,time_period) %>% 
  group_by(table_identifier,ref_area,accounting_entry,sto,activity,unit_measure) %>%
  arrange(time_period,.by_group=TRUE) %>% 
  slice_head(n=1) %>% 
  unique() %>% 
  rename(threshold=time_period)

outlier<- left_join(min_period,df) %>% 
  filter(type=="T") %>% 
  filter(time_period>= threshold) %>% 
  filter(zscore > z_score | zscore < -z_score) %>%  
  select(table_identifier,ref_area,accounting_entry,sto,activity,unit_measure,time_period) %>% 
  mutate(outlier="outlier") %>% 
  unique() %>% 
  mutate(across(where(is.character), as.factor))

if (nrow(outlier)>0) show_DT(outlier)

outlier_f<- outlier %>% 
  select(-time_period)
```


```{r outliers}
temp<- left_join(outlier_f,df) %>% 
  ungroup() %>% 
  left_join(.,NUTS2021) %>% 
  filter(label!="Extra-regio" & type=="T" & NUTS %in% c("2","3")) %>% 
  select(-outlier) %>% 
  left_join(.,outlier) %>% 
    mutate(ref_area=paste0(ref_area,"_",label))

```



```{r charts}

df_charts <- temp %>% 
  unite("series",c(ref_area,activity,accounting_entry,unit_measure)) %>% 
  select(series,table_identifier,sto,outlier,time_period,obs_value) %>% 
  group_by(series) %>% 
  nest() %>% 
  mutate(plot=map2(data,series,~ggplot(.x,aes(time_period,obs_value))+
                     geom_line (size = 0.7, colour = "#0E47CB")+
                     geom_point(data=.x %>% filter(outlier=="outlier"),aes(time_period,obs_value),size=3,colour="#FFCC00")+
                     facet_wrap(~table_identifier~sto)+
                     theme_regacc_line+
                     scale_x_continuous( breaks = breaks_pretty(3), labels = label_number(accuracy = 1),expand=c(0,0.2))+
                     scale_y_continuous( breaks = breaks_pretty(3), labels = label_number(accuracy = 1))+
                     ggtitle(paste0(.y))))
  
for (i in seq_along(df_charts$plot)) print(df_charts$plot[[i]])
```

