---
title: "Regional Accounts checks - Population in Demography"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  html_document: 
    theme: readable
    highlight: monochrome
    code_download: yes
editor_options: 
  chunk_output_type: console
params:
  report: DK
---
<style type="text/css">

body, td {
   font-size: 16px;
   font-family: Cambria;
}
code.r{
  font-size: 14px;
  font-family: Cambria;
}
td {
    font-size: 12px;
    font-family: Cambria;
}
h1, h2, h3, h4, h5, h6 {
   font-size: 20px;
   font-family: Cambria;  
  color: #0E47CB;
}
a {
    font-family: Cambria;
    color: #0E47CB;
}
body { 
background-color: #F3F6FC; 
}
.tocify .list-group-item {
 background-color: #F3F6FC; 
 font-family: Cambria;
 color: #0E47CB;
 font-style:bold

</style>

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = FALSE,
  message = FALSE,
  warning = FALSE
)
```

```{r country, include=FALSE}
country_sel <- params$report
```

```{r load_packages, include=FALSE}
# Packages needed
library(tidyverse)
library(regacc)
library(dataregacc)
library(scales)
library(plotly)
library(rio)
library(data.table)
```

```{r, eval = FALSE}
library(eurostat)
pop_dem<-get_eurostat("demo_r_pjangroup", time_format="num") %>% 
  filter ( sex =="T" & age =="TOTAL") %>% 
  select(-sex,  -age, -unit) %>% 
  group_by(geo) %>% 
  arrange(time,.by_group=TRUE) %>% 
  mutate(dem= round((values+lead(values))/2000,1)) %>% 
  select(-values) %>% 
  ungroup()
saveRDS(pop_dem, "data/eurobase/pop.rds")
```


```{r}
source("utils/palette.R")
source("utils/theme_report.R")

pop_regacc <- list.files(path="data/csv",
                pattern= glob2rx(paste0("*",country_sel,"*")),
                full.names=TRUE) %>% 
  as_tibble() %>% 
  mutate(date=map(value,file.mtime)) %>% 
  unnest(date) %>% 
  arrange(desc(date)) %>% 
  head(1) %>% 
  select(value) %>% 
  pull() %>% 
  fread() %>% 
  mutate(NUTS=as.factor(NUTS)) %>% 
  filter(sto=="POP" & type=="T") 

t1001<- pop_regacc %>% 
  filter(table_identifier=="T1001" & time_period== 2021)

t1200<- pop_regacc %>% 
  filter(table_identifier=="T1200" & time_period< 2021)

pop_regacc<- bind_rows(t1001,t1200) %>% 
  select(table_identifier,ref_area,NUTS,time_period,obs_value) %>%
  rename (regacc = obs_value) 
  

pop_dem <- readRDS("data/eurobase/pop.rds") %>% 
  rename(ref_area=geo,
         time_period=time)

df <- left_join(pop_regacc, pop_dem) %>% 
  na.omit() %>% 
  mutate(reg_dem= round((regacc-dem)*100/dem,1),
         time_period=as.integer(time_period))
  
 
NUTS2021 <- NUTS_2021 %>% 
  filter (country %in% country_sel) %>% #NUTS
   mutate(NUTS=as.factor(NUTS)) %>% 
  droplevels()

df <- left_join(df, NUTS2021)

```


```{r}
p <- ggplot(df, aes(time_period, reg_dem, label = label))+
  geom_line(size = 0.7, colour= "#0E47CB")+
  facet_wrap(~NUTS, scales="free_y")+
  theme_regacc_line+
  scale_y_continuous( breaks = breaks_pretty(4), labels = label_number(accuracy = 1))

ggplotly(p)%>% config(displayModeBar = F)
  
```

```{r,eval = TRUE}
df_plots <-  df %>% 
  select( -reg_dem) %>% 
    pivot_longer(cols = c("regacc","dem"),
                 names_to="series",
                 values_to = "values") %>% 
  group_by(ref_area) %>% 
  nest() 

df_plots <- df_plots %>% 
  mutate(plot = map2(data, ref_area, ~ ggplot(data = .x, aes(x = time_period, y = values, colour= series)) +
                       geom_line(size = 0.9)+
                       theme_regacc_line+
  scale_x_continuous( breaks = breaks_pretty(3), labels = label_number(),expand=c(0,0.2))+
  scale_y_continuous( breaks = breaks_pretty(4), labels = label_number(),expand=c(0,0.2))+
  scale_colour_manual(values=c("#0E47CB", "#FFCC00"))+
    ggtitle(paste0("Geo:", .y)) 
                       ))

walk(df_plots$plot,print)
```

