

base_colour <- "#0E47CB"

theme_shiny_line <- theme_minimal (base_size = 12)+
  theme(plot.background = element_rect(fill= "white", 
                                       colour = base_colour),
        panel.background = element_rect(fill= "#FAFAFA", 
                                        colour = base_colour),
        panel.grid.major.y = element_line(colour=base_colour, 
                                          linetype = "dotted"),
        axis.line.x = element_line(colour=base_colour, 
                                   size =rel(1.2)),
        axis.line.y = element_line(colour= base_colour, 
                                   size= rel(1.2)),
        axis.text.x = element_text(colour=base_colour, 
                                   size =rel (0.8)),
        axis.text.y= element_text(colour= base_colour,
                                  size= rel(1.0),
                                  hjust=0),
        axis.ticks = element_line(size =rel(1.0),
                                  colour = base_colour),
        axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        legend.title = element_blank(),
        legend.key = element_rect(fill= "white",
                                  colour = NA,),
        legend.background = element_rect(fill="white", 
                                         colour = base_colour, 
                                         linetype = "solid"),
        legend.text = element_text(colour= base_colour),
        plot.title = element_text(face= "bold", 
                                  colour =base_colour, 
                                  hjust =0,
                                  size = rel(1.0), 
                                  margin = margin(0,0,0,0)),
        plot.subtitle = element_text(    colour =base_colour, 
                                         hjust =0,
                                         size = rel(1.0), 
                                         margin = margin(0,0,0,0)),
        plot.caption = element_text(    colour =base_colour, 
                                        hjust =1,
                                        size = rel(1.0)),
        plot.tag = element_text(    colour =base_colour, 
                                    hjust =0,
                                    size = rel(1.0)),
        strip.background = element_rect(fill = base_colour, 
                                        colour = NA),
        strip.text = element_text(face = "bold", 
                                  size = 10, 
                                  hjust = 0.2,
                                  colour = "white"),
        strip.placement = "outside",
        panel.spacing = unit(3, "lines")
  )

theme_shiny_scatter <- theme_shiny_line+
  theme(plot.background = element_rect(fill= "white", 
                                       colour = base_colour),
        panel.background = element_rect(fill= "#FAFAFA", 
                                        colour = base_colour),
        panel.grid.major.x = element_line(colour=base_colour, 
                                          linetype = "dotted"),
        axis.line.x = element_line(colour=base_colour, 
                                   size =rel(1.0)),
        axis.line.y = element_line(colour= base_colour, 
                                   size= rel(1.0)),
        axis.text.x = element_text(colour=base_colour, 
                                   size =rel (0.8)),
        axis.text.y= element_text(colour= base_colour, 
                                  size= rel(1.0), 
                                  hjust=0),
        axis.ticks = element_line(size =rel(1.0),
                                  colour = base_colour),
        # axis.title.x = element_text(size = rel(0.9),
        #                             colour=base_colour,
        #                             angle = 0, 
        #                             vjust = 0.5,
        #                             face = "italic"),
        # axis.title.y = element_text(size = rel(0.9),
        #                             colour=base_colour,
        #                             angle = 45, 
        #                             vjust = 0.5,
        #                             face = "italic"),
        plot.title = element_text(face= "bold", 
                                  colour =base_colour, 
                                  hjust =0,
                                  size = rel(1.0), 
                                  margin = margin(0,0,0,0)),
        plot.subtitle = element_text(    colour =base_colour, 
                                         hjust =0,
                                         size = rel(1.1), 
                                         margin = margin(0,0,0,0)),
        plot.caption = element_text(    colour =base_colour, 
                                        hjust =1,
                                        size = rel(1.0)),
        plot.tag = element_text(    colour =base_colour, 
                                    hjust =0,
                                    size = rel(1.0)),
        strip.background = element_rect(fill = base_colour, 
                                        colour = NA),
        strip.text = element_text(face = "bold", 
                                  size = 10, 
                                  hjust = 0.2,
                                  colour = "white"),
        strip.placement = "outside",
        panel.spacing = unit(3, "lines")
  )



