---
title: "Release 2022"
author: "Luis Biedma"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: 
  html_document: 
    theme: readable
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = FALSE,
	message = FALSE,
	warning = FALSE
)
```



```{r , message=FALSE, warning=FALSE, cache = FALSE}
library(tidyverse)
library(here)
library(arrow)
library(DT)
library(sf)
library(tmap)
library(formattable)
```

## Main results: GDP per capita in PPS as % of the EU average 

```{r, message=FALSE, warning=FALSE, cache = FALSE}
new<-read_parquet(here("data","denodo","all_primary.parquet")) %>% 
  filter(activity %in% c("_T","_Z") & prices!="LR" & type=="V" & transformation !="A3" & NUTS %in% c("0","2") & time_period >=2020 & table_identifier =="T1001_1200" & unit_measure =="PE_B6_R_B6_POP" & !country %in% c("TR","AL","ME","MK","NO","RS")) %>% 
  select(country,NUTS,ref_area,time_period,obs_value) %>% 
  mutate(obs_value=janitor::round_half_up(obs_value)) %>% 
  pivot_wider(names_from=time_period,
               values_from=obs_value) %>%
  drop_na() 
  
as.datatable(formattable(new, list(`2020` = color_bar("#B656BD"),
                                   `2021` = color_bar("#B656BD"))),  filter = "top", class = "stripe hover", extensions = "Buttons",
             options = list(  lengthMenu = list(c(20,50,200, -1), c("20","50","200", "All")),
                              pageLength = 50, autoWidth = TRUE,  dom = "Blfrtip", buttons = c("excel")),
             rownames= FALSE
)  

```

```{r, message=FALSE, warning=FALSE}
nuts<- dataregacc::NUTS_shape

sf<- left_join (nuts, new) 

sf<- sf %>% 
  filter(!CNTR_CODE %in% c("UK","IS","NO","CH","LI"))

tmap_mode("view")
sf %>% filter(LEVL_CODE=="2")  %>% 
tm_shape() +
tm_fill("2021", popup.vars = c("ref_area","NAME_LATN","2021"), palette="viridis", style="quantile",  title="GDP per capita in PPS as % EU average, 2021")+
  tm_borders()

```
```

